version: '2'
services:
  knowledge-db:
    image: postgres:9.6.6
    labels:
      io.rancher.container.hostname_override: container_name
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: knowledge_production
    restart: unless-stopped

  knowledge-app:
    image: koda/docker-knowledge
    labels:
      io.rancher.container.hostname_override: container_name
    volumes:
      - knowledge-volume:/root/.knowledge
    links: [knowledge-db]
    ports: ["8082:8080"]
    restart: always

volumes:
  knowledge-volume:
    driver: rancher-ebs
    driver_opts:
      size: 10
      volumeType: gp2
      iops: 1000
      ec2_az: ap-northeast-2
